name: Release
on:
  pull_request:
    branches:
      - 'release\/v[0-9]{1,3}_[0-9]{1,3}_[0-9]{1,3}'
    types: [closed]
jobs:
  release:
    if: github.event.pull_request.merged == true
    name: Release botpress version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      # Create an array of version to push to the Dockerhub registery
      - name: Deploy via Jenkins
        id: Deploy
        run: |
          HEAD_REF=${{github.head_ref}}
          sudo apt-get update && sudo apt-get install jq
          BRANCH_LABEL=$(echo "${HEAD_REF#release\/}") # transform release/v12_12_12 to v12_12_12
          BRANCH_NAME=("${HEAD_REF/#/origin/}")
          echo "${BRANCH_NAME}"
          echo "${BRANCH_LABEL}"