name: Release
on: [pull_request]
jobs:
  release:
    name: Release botpress version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      # Create an array of version to push to the Dockerhub registery
      - name: Deploy via Jenkins
        id: Deploy
        run: |
          apt-get update && apt-get jq
          BRANCH_LABEL=($(echo ${GITHUB_REF#refs/heads/release})) # transform release/v12_12_12 to v12_12_12
          BRANCH_NAME=($(echo "${GITHUB_REF#refs/heads}/#/origin\/"))

          echo "${BRANCH_NAME}"
          echo "${BRANCH_LABEL}"